### PR TITLE
Remove a duplicate from readme.md

### PR DESCRIPTION
**Pull request by vsemozhetbyt**

### CODE REVIEW

**Comment by zeke** [comment]
This is intentional. The URL is the same, but that project can be used to answer both of those questions. Thanks for noticing, though!

**Comment by zeke** [comment]
I will update the readme with some Gitlab stats to make that more obvious.

**Comment by vsemozhetbyt** [comment]
Oh, I did not notice GitHub != GitLab. I am sorry for bothering in vain,

**Comment by zeke** [comment]
No worries. This actually helped me find a bug in https://github.com/nice-registry/all-the-package-repos where non-GitHub repos are being collected as objects instead of URL strings. Working on a fix now. Thanks!

**Pull request closed without merging**
